### ISSUE TITLE
Additional Functions ? pitch bend, modulation Octave up.down.

### ISSUE THREAD

**Issue by stumax** [ihavenotea/Keytar-MIDI-Connector#2]
Hi,

Just found this and its just what I needed, I use one of these with a live band so having it work wirelessly it fantastic.

Just wondering if there's any plans to make the pitch/bend / mod slider or the octave up and down buttons work ?

If anyone can help on this it would be much appreciated !

sTu

**Comment by jonyo** [comment]
@stumax I know it's been a looong time but if you are still looking, I've added octave change control on my own fork of this project, and as I have time I'll be adding other functionality that mimics what the MIDI port does.

@fskai I know it's been a long time, but would you be interested in a PR once I get all the functionality added in?

**Comment by stumax** [comment]
Hi,

Definitely interested to see where you go with this. 

Although I have another version working great at the mo (see https://github.com/nardi/rbkey-midi ).

It has all ribbon control and buttons functioning, but if you need someone to give it a test i'm more than happy to help :) 

sTu

**Comment by jonyo** [comment]
@stumax I tried that solution first, for whatever reason it wasn't working.  On my macbook pro running OSX Yosemite, I would run rbkey-midi and it would ask which MIDI port to use, but above that the "list" of available MIDI ports would be empty.  Think it might be something with Yosemite, or possibly something to do with running on 64bit or something.  If that one has everything working though, might be worth it for me to try troubleshooting it further, don't want to spend tons of time re-inventing the wheel if I can get that one to work!

Thanks! :+1:

**Comment by stumax** [comment]
It sounds like you need to set up the loopback device. I have it running fine on Yosemite. 

I made a note of the install instructions, it went like this - 

1.Install node from http://nodejs.org/

2.add to path
export PATH=/usr/local/git/bin:/usr/local/bin:$PATH

3. install rbkey

sudo npm install -g rbkey-midi

4. should see nag box , "the git command requires the command line developer tools" Choose install

5. retry step 4

6. Set up loopback device 
Applications > Utilities > Audio MIDI setup

In Audio MIDI setup go to the menu Window > Show MIDI set up
Double click the IAC driver icon
Click the "Device is online checkbox"
Clck the + sign , name the new port something like RB3 Keytar
delete the other port listed

Hope that helps, if you get stuck give me a yell. Also the author is very helpful if it's something I can't help with :)

Cheers,
sTu

**Comment by stumax** [comment]
These instructions were from Mavericks, I think on Yosemite it doesn't need to ask for the developer tools bit...

**Comment by jonyo** [comment]
Thanks!  That was it...  I found instructions on that part of it before but they were so out of date at one of the steps it was telling me to go into something that simply didn't exist.  Now it's working like a charm, thanks!  :)

**Comment by stumax** [comment]
Great, glad it's sorted !

The only improvement I could think of is to add functionality to the up/down/left/right buttons... It would be good if these could be used for 8ve up/down perhaps. 

What are you using it with ? I'm running it with Mainstage for live stuff, works a treat !

sTu

**Comment by jonyo** [comment]
At the moment, just using it for fun, using garage band.  Was thinking of checking out something like Synthesia to re-teach myself how to play (used to play piano years ago).  The lack of a full range was bugging me so the main thing I was looking for was octave control.

**Comment by ihavenotea** [comment]
I am not actively maintaining this project anymore. I am going to close out the issue, as I try and only keep things open if they are things I will be doing _eventually_. If anyone forks this and get's the added functionality working that will be awesome.

Thanks to everyone for all the interest in this. I hope it has brought you all some joy. :purple_heart: :musical_keyboard:
